version: "3.9"

services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=
#      - POSTGRES_USER=
#      - POSTGRES_PASSWORD=
#    ports:
#      - 15432:5432
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/main
    expose:
      - 8000
#    depends_on:
#      - db
    environment:
#      - DB_NAME=
#      - DB_USER=
#      - USER_PASSWORD=
#      - DB_HOST=db
#      - DB_PORT=5432
      - SECRET_KEY='django-insecure-p4hldk)!^n4(rrrzlz_^-c%!g$v9$a8e)7kobrlz6!qvtk#7gb'
      - DEBUG_VALUE=True
