# Generated by Django 4.0.6 on 2022-07-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_view_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
